all:
	xelatex coverletter.tex
	evince coverletter.pdf &
install:
	sudo apt-get install texlive texlive-latex-extra texlive-xetex
	sudo apt-get install texlive-math-extra
	sudo apt-get install texlive-bibtex-extra
clean:
	rm *.log *.aux
